// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// app/layout.js
// import '../styles/globals.css'

import "./globals.css";

import { AuthProvider } from './context/AuthContext'
import { TaskProvider } from './context/TaskContext'

import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'TickTick Clone',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TaskProvider>
            {children}
            <ToastContainer/>
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
